# Get client id and secret code - https://dev.twitch.tv/console/apps
client_id:     ''
client_secret: ''

# https://twitchapps.com/tmi/ (optional)
oauth_token: ''

# Webhook for discord notifications (discord: true)
webhook_url: '' # Edit webhook.json (I advise discohook.org)

# Toggle features
discord:      false
duration:     false # unstable
follow:       false
cheer:        true
sub:          true
sub_gift:     true
sub_mystery:  true

# Custom messages
# How to make colorful text       - https://www.digminecraft.com/lists/color_list_pc.php
# How to make cool colorful text  - https://jtvjan.nl/tools/rainbowtext.html

# Possible placeholders
# stream_up:        {streamer}, {game}, {title}
# stream_down:      {streamer}
# stream_duration:  {streamer}, {game}, {title}, {duration}
# on_follow:        {streamer}, {user}
# on_cheer:         {streamer}, {user}, {bits}, {message}, {sub_months}, {sub_tier}
# on_sub:           {streamer}, {user}, {sub_plan}, {months}, {sub_streak}
# on_sub_gift:      {streamer}, {user}, {gifted}, {sub_plan}, {gift_months}, {months}, {sub_streak}
# on_sub_mystery:   {streamer}, {user}, {sub_plan}, {subs_gifted}, {subs_gifted_total}

stream_up:        '§l§d[TwitchBot]§f {streamer} has gone live: {title}'
stream_down:      '§l§d[TwitchBot]§f {streamer} has stopped streaming.'
stream_duration:  '§l§d[TwitchBot]§f {streamer} has been streaming for %s.'
on_follow:        '§l§d[TwitchBot]§f {user} just followed!'
on_cheer:         '§l§d[TwitchBot]§f {user} just cheered {bits} bits!'
on_sub:           '§l§d[TwitchBot]§f {user} just subscribed for {months} months!'
on_sub_gift:      '§l§d[TwitchBot]§f Thank you {user} for gifting {subs_gifted} subs to {gifted} ❤'
on_sub_mystery:   '§l§d[TwitchBot]§f Thank you {gifter} for gifting {subs_gifted} subs ❤'

# Duration alerts settings (duration: false to disable)
round_to:      30      # Nearest minute for rounding.
message_delay: 1805    # Delay between alerts in seconds.

# Which channel events you want to announce.
channels:
  - bestchannelintheworld
